const texts = {
  en: {
    prompt: "English",
    texts: {
      correct: "Well done! You played the note <b>{note}</b>.",
      incorrect: "You played the note <b>{note}</b>!",
      desiredNote: " Desired note is <b>{note}</b>.",
      tryAgain: " Try again!",
      playNote: "Play the given note!",
      activating : "Activating microphone and initializing note detection...",
      starting: "Starting note detection...",
      loadingModel: "Loading model...",
      modelLoaded: "Model loaded."
    },
    main: {
      title: "Note Trainer",
      instruction: "Play the note on the <span id=\"instrumentName\"></span>:",
      continue: "Continue",
      startButton: "Start",
      stopButton: "Stop"
      },
    options: {
      optionsTitle: "Options",
      showNoteNameCheckbox: "Show Note Names",
      playNoteCheckbox: "Play Note",
      useBassClefCheckbox: "Activate ",
      showSummaryCheckbox: "Show Summary",
      pauseInput: "Pause",
      toleranceInput: "Tolerance (Hz)",
      instrumentSaxTenorRadio: "Tenor Sax",
      instrumentSaxAltRadio: "Alto Sax",
      instrumentRegularRadio: "Piano",
      smallRangeRadio: "Small",
      middleRangeRadio: "Middle",
      largeRangeRadio: "Large",
      noteFilterCheckbox: "Note Filter",
      noteFilterInput: "Filter Notes",
      showSharpCheckbox: "Activate ",
      showFlatCheckbox: "Activate ",
      languageSelector: "Language",
      instrumentTuning: "Instrument Tuning",
      noteRange: "Note Range",
      accidentals: "Accidentals"
    },
    tooltips: {
      showNoteNameCheckboxLabel: "Shows the note name over the staff.\n(Disable this option to learn the direct translation from note to position.)",
      playNoteCheckboxLabel: "Plays the newly suggested note briefly.",
      useBassClefCheckboxLabel: "Switches to bass clef if needed.",
      showSummaryCheckboxLabel: "Shows a summary when the stop button is pressed.",
      pauseCheckboxLabel: "Specifies the pause (in milliseconds) between a successful note and the next suggested note.",
      toleranceInputLabel: "Allows the specified deviation in Hertz for note recognition.",
      noteFilterCheckboxLabel: "Selects all notes matching the letters in the list. You can also indicate the octave like 'C4 D4 C5', or b und #.",
      showSharpCheckboxLabel: "Selects notes with ♯ (Cis, Dis, Fis, Gis, Ais).",
      showFlatCheckboxLabel: "Selects notes with ♭ (Des, Es, Ges, As, bB).",
      instrumentSaxTenorRadioLabel: "The tenor saxophone is notated a major ninth (14 semitones) higher than it sounds and is therefore tuned in B♭.",
      instrumentSaxAltRadioLabel: "The alto saxophone is notated a major sixth (9 semitones) higher than it sounds and is therefore tuned in E♭.",
      instrumentRegularRadioLabel: "Most instruments are notated as they sound.",
      smallRangeRadioLabel: "Selects just a small range of notes.",
      middleRangeRadioLabel: "Selects a medium range of notes.",
      largeRangeRadioLabel: "Selects a large range of notes."
    },
    summary: {
      summaryHeading: "Summary",
      summaryMessage: "Notes you should practice:",
      successMessage: "Great! No mistakes made!",
      closeButton: "Close",
    }
  },
  de: {
    prompt: "Deutsch",
    texts: {
      correct: "Gut gemacht! Du hast den Ton <b>{note}</b> gespielt.",
      incorrect: "Du hast den Ton <b>{note}</b> gespielt!",
      desiredNote: " Gewünschter Ton ist <b>{note}</b>.",
      tryAgain: " Versuche es noch einmal!",
      playNote: "Spiele den angegebenen Ton!",
      activating : "Aktiviere Mikrofon und initialisiere Notenerkennung...",
      starting: "Starte Notenerkennung...",
      loadingModel: "Lade Modell...",
      modelLoaded: "Modell geladen."
    },
    main: {
      title: "Noten Trainer",
      instruction: "Spiele den Ton auf dem <span id=\"instrumentName\"></span>:",
      continue: "Weiter",
      startButton: "Start",
      stopButton: "Stopp"
    },
    options: {  
      optionsTitle: "Optionen",
      showNoteNameCheckbox: "Zeige Notennamen",
      playNoteCheckbox: "Spiele Ton",
      useBassClefCheckbox: "Aktiviere ",
      showSummaryCheckbox: "Zeige Zusammenfassung",
      pauseInput: "Pause",
      toleranceInput: "Toleranz (Hz)",
      instrumentSaxTenorRadio: "Tenor Sax",
      instrumentSaxAltRadio: "Alt Sax",
      instrumentRegularRadio: "Klavier",
      smallRangeRadio: "Klein",
      middleRangeRadio: "Mittel",
      largeRangeRadio: "Groß",
      noteFilterCheckbox: "Noten Filter",
      noteFilterInput: "Noten filtern",
      showSharpCheckbox: "Aktiviere ",
      showFlatCheckbox: "Aktiviere ",
      languageSelector: "Sprache",
      instrumentTuning: "Instrumenten Stimmung",
      noteRange: "Notenraum",
      accidentals: "Vorzeichen"
    },
    tooltips: {
      showNoteNameCheckboxLabel: "Zeigt den Notennamen über den Noteninien an.\n(Deaktiviere diese Option um die direkte Übersetzung von Note zu Position zu lernen.)",
      playNoteCheckboxLabel: "Spielt kurz den neu vorgeschlagenen Ton ab.",
      useBassClefCheckboxLabel: "Wechselt bei Bedarf in den Bassschlüssel.",
      showSummaryCheckboxLabel: "Zeigt eine Zusammenfassung wenn die Stopp-Taste gedrückt wird.",
      pauseCheckboxLabel: "Gibt die Pause (in Millisekunden) zwischen einem erfolgreichen Ton und dem nächsten vorgeschlagenen Ton an.",
      toleranceInputLabel: "Erlaubt bei der Ton-Erkennung die angegebene Abweichung in Hertz.",
      noteFilterCheckboxLabel: "Wählt alle Töne aus, die den Buchstaben in der Liste entsprechen.\nEs kann auch die Oktave angegeben werden, z.B. 'C4 D4 C5', oder b und #.",
      showSharpCheckboxLabel: "Wählt auch Noten mit ♯ (Cis, Dis, Fis, Gis, Ais) aus.",
      showFlatCheckboxLabel: "Wählt auch Noten mit ♭ (Des, Es, Ges, As, B) aus.",
      instrumentSaxTenorRadioLabel: "Das Tenorsaxophon notiert eine große None (14 Halbtöne) höher als klingend und ist damit in B gestimmt.",
      instrumentSaxAltRadioLabel: "Das Altsaxophon notiert eine große Sexte (9 Halbtöne) höher als klingend und ist damit in Es gestimmt.",
      instrumentRegularRadioLabel: "Die meisten Instrumente notieren wie klingend.",
      smallRangeRadioLabel: "Wählt nur einen kleinen Notenraum aus.",
      middleRangeRadioLabel: "Wählt einen mittleren Notenraum aus.",
      largeRangeRadioLabel: "Wählt einen großen Notenraum aus."
    },
    summary: {
      summaryHeading: "Zusammenfassung",
      summaryMessage: "Noten, die Du noch üben solltest:",
      successMessage: "Super! Keine Fehler gemacht!",
      closeButton: "Schließen",
    }
  },
  it: {
    prompt: "Italiano",
    texts: {
      correct: "Ben fatto! Hai suonato la nota <b>{note}</b>.",
      incorrect: "Hai suonato la nota <b>{note}</b>!",
      desiredNote: " La nota desiderata è <b>{note}</b>.",
      tryAgain: " Riprova!",
      playNote: "Suona la nota indicata!",
      activating : "Attivazione del microfono e inizializzazione del rilevamento delle note...",
      starting: "Avvio del rilevamento delle note...",
      loadingModel: "Caricamento del modello...",
      modelLoaded: "Modello caricato."
    },
    main: {
      title: "Allenatore di Note",
      instruction: "Suona la nota sul <span id=\"instrumentName\"></span>:",
      continue: "Continua",
      startButton: "Inizia",
      stopButton: "Ferma"
    },
    options: {
      optionsTitle: "Opzioni",
      showNoteNameCheckbox: "Mostra i nomi delle note",
      playNoteCheckbox: "Suona la nota",
      useBassClefCheckbox: "Attiva ",
      showSummaryCheckbox: "Mostra riepilogo",
      pauseInput: "Pausa",
      toleranceInput: "Tolleranza (Hz)",
      instrumentSaxTenorRadio: "Sax Tenore",
      instrumentSaxAltRadio: "Sax Alto",
      instrumentRegularRadio: "Pianoforte",
      smallRangeRadio: "Piccolo",
      middleRangeRadio: "Medio",
      largeRangeRadio: "Grande",
      noteFilterCheckbox: "Filtro note",
      noteFilterInput: "Filtra note",
      showSharpCheckbox: "Attiva ",
      showFlatCheckbox: "Attiva ",
      languageSelector: "Lingua",
      instrumentTuning: "Accordatura dello strumento",
      noteRange: "Gamma di note",
      accidentals: "Alterazioni"
    },
    tooltips: {
      showNoteNameCheckboxLabel: "Mostra il nome della nota sopra il pentagramma.\n(Disabilita questa opzione per imparare la traduzione diretta da nota a posizione.)",
      playNoteCheckboxLabel: "Suona brevemente la nota appena suggerita.",
      useBassClefCheckboxLabel: "Passa alla chiave di basso se necessario.",
      showSummaryCheckboxLabel: "Mostra un riepilogo quando viene premuto il pulsante di stop.",
      pauseCheckboxLabel: "Specifica la pausa (in millisecondi) tra una nota corretta e la prossima nota suggerita.",
      toleranceInputLabel: "Consente la deviazione specificata in Hertz per il riconoscimento delle note.",
      noteFilterCheckboxLabel: "Seleziona tutte le note che corrispondono alle lettere nell'elenco. Puoi anche indicare l'ottava come 'C4 D4 C5', o b e #.",
      showSharpCheckboxLabel: "Seleziona le note con ♯ (Do#, Re#, Fa#, Sol#, La#).",
      showFlatCheckboxLabel: "Seleziona le note con ♭ (Re♭, Mi♭, Sol♭, La♭, Si♭).",
      instrumentSaxTenorRadioLabel: "Il sassofono tenore è notato una nona maggiore (14 semitoni) più alta di come suona ed è quindi accordato in Si♭.",
      instrumentSaxAltRadioLabel: "Il sassofono alto è notato una sesta maggiore (9 semitoni) più alta di come suona ed è quindi accordato in Mi♭.",
      instrumentRegularRadioLabel: "La maggior parte degli strumenti è notata come suona.",
      smallRangeRadioLabel: "Seleziona solo una piccola gamma di note.",
      middleRangeRadioLabel: "Seleziona una gamma media di note.",
      largeRangeRadioLabel: "Seleziona una grande gamma di note."
    },
    summary: {
      summaryHeading: "Riepilogo",
      summaryMessage: "Note che dovresti praticare:",
      successMessage: "Ottimo! Nessun errore!",
      closeButton: "Chiudi",
    }
  },
  fr: {
    prompt: "Français",
    texts: {
      correct: "Bien joué! Vous avez joué la note <b>{note}</b>.",
      incorrect: "Vous avez joué la note <b>{note}</b>!",
      desiredNote: " La note désirée est <b>{note}</b>.",
      tryAgain: " Réessayez!",
      playNote: "Jouez la note donnée!",
      activating : "Activation du microphone et initialisation de la détection des notes...",
      starting: "Démarrage de la détection des notes...",
      loadingModel: "Chargement du modèle...",
      modelLoaded: "Modèle chargé."
    },
    main: {
      title: "Entraîneur de Notes",
      instruction: "Jouez la note sur le <span id=\"instrumentName\"></span>:",
      continue: "Continuer",
      startButton: "Démarrer",
      stopButton: "Arrêter"
    },
    options: {
      optionsTitle: "Options",
      showNoteNameCheckbox: "Afficher les noms des notes",
      playNoteCheckbox: "Jouer la note",
      useBassClefCheckbox: "Activer ",
      showSummaryCheckbox: "Afficher le résumé",
      pauseInput: "Pause",
      toleranceInput: "Tolérance (Hz)",
      instrumentSaxTenorRadio: "Sax Ténor",
      instrumentSaxAltRadio: "Sax Alto",
      instrumentRegularRadio: "Piano",
      smallRangeRadio: "Petit",
      middleRangeRadio: "Moyen",
      largeRangeRadio: "Grand",
      noteFilterCheckbox: "Filtre de notes",
      noteFilterInput: "Filtrer les notes",
      showSharpCheckbox: "Activer ",
      showFlatCheckbox: "Activer ",
      languageSelector: "Langue",
      instrumentTuning: "Accordage de l'instrument",
      noteRange: "Gamme de notes",
      accidentals: "Altérations"
    },
    tooltips: {
      showNoteNameCheckboxLabel: "Affiche le nom de la note au-dessus de la portée.\n(Désactivez cette option pour apprendre la traduction directe de la note à la position.)",
      playNoteCheckboxLabel: "Joue brièvement la note nouvellement suggérée.",
      useBassClefCheckboxLabel: "Passe à la clé de fa si nécessaire.",
      showSummaryCheckboxLabel: "Affiche un résumé lorsque le bouton d'arrêt est enfoncé.",
      pauseCheckboxLabel: "Spécifie la pause (en millisecondes) entre une note correcte et la prochaine note suggérée.",
      toleranceInputLabel: "Permet la déviation spécifiée en Hertz pour la reconnaissance des notes.",
      noteFilterCheckboxLabel: "Sélectionne toutes les notes correspondant aux lettres de la liste. Vous pouvez également indiquer l'octave comme 'C4 D4 C5', ou b et #.",
      showSharpCheckboxLabel: "Sélectionne les notes avec ♯ (Do#, Ré#, Fa#, Sol#, La#).",
      showFlatCheckboxLabel: "Sélectionne les notes avec ♭ (Ré♭, Mi♭, Sol♭, La♭, Si♭).",
      instrumentSaxTenorRadioLabel: "Le saxophone ténor est noté une neuvième majeure (14 demi-tons) plus haut qu'il ne sonne et est donc accordé en Si♭.",
      instrumentSaxAltRadioLabel: "Le saxophone alto est noté une sixte majeure (9 demi-tons) plus haut qu'il ne sonne et est donc accordé en Mi♭.",
      instrumentRegularRadioLabel: "La plupart des instruments sont notés comme ils sonnent.",
      smallRangeRadioLabel: "Sélectionne juste une petite gamme de notes.",
      middleRangeRadioLabel: "Sélectionne une gamme moyenne de notes.",
      largeRangeRadioLabel: "Sélectionne une grande gamme de notes."
    },
    summary: {
      summaryHeading: "Résumé",
      summaryMessage: "Notes que vous devriez pratiquer:",
      successMessage: "Super! Aucun erreur!",
      closeButton: "Fermer",
      topIncorrectNotes: "top 3 notes"
    }
  },
  es: {
    prompt: "Español",
    texts: {
      correct: "¡Bien hecho! Tocaste la nota <b>{note}</b>.",
      incorrect: "¡Tocaste la nota <b>{note}</b>!",
      desiredNote: " La nota deseada es <b>{note}</b>.",
      tryAgain: " ¡Inténtalo de nuevo!",
      playNote: "¡Toca la nota dada!",
      activating : "Activando el micrófono e inicializando la detección de notas...",
      starting: "Iniciando la detección de notas...",
      loadingModel: "Cargando modelo...",
      modelLoaded: "Modelo cargado."
    },
    main: {
      title: "Entrenador de Notas",
      instruction: "Toca la nota en el <span id=\"instrumentName\"></span>:",
      continue: "Continuar",
      startButton: "Iniciar",
      stopButton: "Detener"
    },
    options: {
      optionsTitle: "Opciones",
      showNoteNameCheckbox: "Mostrar nombres de notas",
      playNoteCheckbox: "Tocar nota",
      useBassClefCheckbox: "Activar ",
      showSummaryCheckbox: "Mostrar resumen",
      pauseInput: "Pausa",
      toleranceInput: "Tolerancia (Hz)",
      instrumentSaxTenorRadio: "Sax Tenor",
      instrumentSaxAltRadio: "Saxo Alto",
      instrumentRegularRadio: "Piano",
      smallRangeRadio: "Pequeño",
      middleRangeRadio: "Medio",
      largeRangeRadio: "Grande",
      noteFilterCheckbox: "Filtro de notas",
      noteFilterInput: "Filtrar notas",
      showSharpCheckbox: "Activar ",
      showFlatCheckbox: "Activar ",
      languageSelector: "Idioma",
      instrumentTuning: "Afinación del instrumento",
      noteRange: "Rango de notas",
      accidentals: "Alteraciones"
    },
    tooltips: {
      showNoteNameCheckboxLabel: "Muestra el nombre de la nota sobre el pentagrama.\n(Desactiva esta opción para aprender la traducción directa de la nota a la posición.)",
      playNoteCheckboxLabel: "Reproduce brevemente la nota recién sugerida.",
      useBassClefCheckboxLabel: "Cambia a la clave de fa si es necesario.",
      showSummaryCheckboxLabel: "Muestra un resumen cuando se presiona el botón de detener.",
      pauseCheckboxLabel: "Especifica la pausa (en milisegundos) entre una nota correcta y la siguiente nota sugerida.",
      toleranceInputLabel: "Permite la desviación especificada en Hertz para el reconocimiento de notas.",
      noteFilterCheckboxLabel: "Selecciona todas las notas que coinciden con las letras en la lista. También puedes indicar la octava como 'C4 D4 C5', o b y #."
    }
  }
};